### ISSUE TITLE
WebSocket API doesn't work

### ISSUE THREAD

**Issue by tune** [codefirst/AsakusaSatellite#19]
After installation, I found that AsakusaSatellite indicates that WebSocket API is not working correctly.

I found setting in config/message_pusher.yml and modified as follows.

``` YAML
default: <%= ENV['MESSAGE_PUSHER_ENGINE'] || 'socky' %>

engines:
 socky:
  http: http://192.168.1.1:3002/http
  web_socket: ws://192.168.1.1:3002/websocket
  app: as
  secret: secret
```

But still WebSocket does not work.

I invoke WebSocket server with following command.

> bundle exec thin -R socky/config.ru -p3002 -t0 start
